// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsInscripcion.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsInscripcion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InscripcionDbContext))]
    partial class InscripcionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("DuracionSemestres")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_semestres");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_carreras");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_carreras_codigo");

                    b.ToTable("carreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "ING-SIS",
                            DuracionSemestres = 10,
                            Nombre = "Ingeniería de Sistemas"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "ADM",
                            DuracionSemestres = 8,
                            Nombre = "Administración de Empresas"
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("SemestreActual")
                        .HasColumnType("integer")
                        .HasColumnName("semestre_actual");

                    b.HasKey("Id")
                        .HasName("pk_estudiantes");

                    b.HasIndex("CarreraId")
                        .HasDatabaseName("ix_estudiantes_carrera_id");

                    b.ToTable("estudiantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Nombre = "Ana",
                            SemestreActual = 2
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 1,
                            Nombre = "Carlos",
                            SemestreActual = 1
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.HistorialAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_id");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("nota");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("periodo");

                    b.HasKey("Id")
                        .HasName("pk_historial_academico");

                    b.HasIndex("MateriaId")
                        .HasDatabaseName("ix_historial_academico_materia_id");

                    b.HasIndex("EstudianteId", "MateriaId", "Periodo")
                        .IsUnique()
                        .HasDatabaseName("ux_historial_estudiante_materia_periodo");

                    b.ToTable("historial_academico", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Aprobada",
                            EstudianteId = 1,
                            MateriaId = 1,
                            Nota = 4.5m,
                            Periodo = "2026-1"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Aprobada",
                            EstudianteId = 1,
                            MateriaId = 3,
                            Nota = 4.0m,
                            Periodo = "2026-1"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Reprobada",
                            EstudianteId = 1,
                            MateriaId = 2,
                            Nota = 2.0m,
                            Periodo = "2026-1"
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.HorarioMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_id");

                    b.HasKey("Id")
                        .HasName("pk_horario_materia");

                    b.HasIndex("MateriaId")
                        .HasDatabaseName("ix_horario_materia_materia_id");

                    b.ToTable("horario_materia", null, t =>
                        {
                            t.HasCheckConstraint("ck_horario_materia_rango", "hora_inicio < hora_fin");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaSemana = "Lunes",
                            HoraFin = new TimeOnly(8, 0, 0),
                            HoraInicio = new TimeOnly(6, 0, 0),
                            MateriaId = 1
                        },
                        new
                        {
                            Id = 2,
                            DiaSemana = "Miercoles",
                            HoraFin = new TimeOnly(8, 0, 0),
                            HoraInicio = new TimeOnly(6, 0, 0),
                            MateriaId = 1
                        },
                        new
                        {
                            Id = 3,
                            DiaSemana = "Lunes",
                            HoraFin = new TimeOnly(11, 0, 0),
                            HoraInicio = new TimeOnly(9, 0, 0),
                            MateriaId = 2
                        },
                        new
                        {
                            Id = 4,
                            DiaSemana = "Martes",
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            MateriaId = 3
                        },
                        new
                        {
                            Id = 5,
                            DiaSemana = "Viernes",
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            MateriaId = 4
                        },
                        new
                        {
                            Id = 6,
                            DiaSemana = "Viernes",
                            HoraFin = new TimeOnly(11, 0, 0),
                            HoraInicio = new TimeOnly(9, 0, 0),
                            MateriaId = 5
                        },
                        new
                        {
                            Id = 7,
                            DiaSemana = "Lunes",
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            MateriaId = 6
                        },
                        new
                        {
                            Id = 8,
                            DiaSemana = "Miercoles",
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            MateriaId = 6
                        },
                        new
                        {
                            Id = 9,
                            DiaSemana = "Martes",
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            MateriaId = 7
                        },
                        new
                        {
                            Id = 10,
                            DiaSemana = "Jueves",
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            MateriaId = 7
                        },
                        new
                        {
                            Id = 11,
                            DiaSemana = "Martes",
                            HoraFin = new TimeOnly(14, 0, 0),
                            HoraInicio = new TimeOnly(12, 0, 0),
                            MateriaId = 8
                        },
                        new
                        {
                            Id = 12,
                            DiaSemana = "Jueves",
                            HoraFin = new TimeOnly(16, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0),
                            MateriaId = 9
                        },
                        new
                        {
                            Id = 13,
                            DiaSemana = "Miercoles",
                            HoraFin = new TimeOnly(16, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0),
                            MateriaId = 10
                        },
                        new
                        {
                            Id = 14,
                            DiaSemana = "Jueves",
                            HoraFin = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(16, 0, 0),
                            MateriaId = 11
                        },
                        new
                        {
                            Id = 15,
                            DiaSemana = "Sabado",
                            HoraFin = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0),
                            MateriaId = 12
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("estado");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTimeOffset>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inscripcion");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_id");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("periodo_academico");

                    b.HasKey("Id")
                        .HasName("pk_inscripciones");

                    b.HasIndex("MateriaId", "PeriodoAcademico")
                        .HasDatabaseName("ix_inscripciones_materia_id_periodo_academico");

                    b.HasIndex("EstudianteId", "MateriaId", "PeriodoAcademico")
                        .IsUnique()
                        .HasDatabaseName("ux_inscripciones_activa")
                        .HasFilter("estado = 'Activa'");

                    b.ToTable("inscripciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Activa",
                            EstudianteId = 1,
                            FechaInscripcion = new DateTimeOffset(new DateTime(2026, 8, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MateriaId = 4,
                            PeriodoAcademico = "2026-2"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Activa",
                            EstudianteId = 2,
                            FechaInscripcion = new DateTimeOffset(new DateTime(2026, 8, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MateriaId = 9,
                            PeriodoAcademico = "2026-2"
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("Creditos")
                        .HasColumnType("integer")
                        .HasColumnName("creditos");

                    b.Property<int>("CuposMaximos")
                        .HasColumnType("integer")
                        .HasColumnName("cupos_maximos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("Id")
                        .HasName("pk_materias");

                    b.HasIndex("CarreraId")
                        .HasDatabaseName("ix_materias_carrera_id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_materias_codigo");

                    b.ToTable("materias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Codigo = "MAT101",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Cálculo I",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 1,
                            Codigo = "FIS101",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Física I",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 3,
                            CarreraId = 1,
                            Codigo = "PRG101",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Programación I",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 4,
                            CarreraId = 1,
                            Codigo = "ETI101",
                            Creditos = 2,
                            CuposMaximos = 30,
                            Nombre = "Ética",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 5,
                            CarreraId = 1,
                            Codigo = "HUM101",
                            Creditos = 2,
                            CuposMaximos = 30,
                            Nombre = "Humanidades",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 6,
                            CarreraId = 1,
                            Codigo = "MAT201",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Cálculo II",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 7,
                            CarreraId = 1,
                            Codigo = "PRG201",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Programación II",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 8,
                            CarreraId = 1,
                            Codigo = "EST201",
                            Creditos = 3,
                            CuposMaximos = 30,
                            Nombre = "Estadística",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 9,
                            CarreraId = 1,
                            Codigo = "ALG201",
                            Creditos = 3,
                            CuposMaximos = 1,
                            Nombre = "Álgebra Lineal",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 10,
                            CarreraId = 1,
                            Codigo = "EDD301",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Estructuras de Datos",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 11,
                            CarreraId = 1,
                            Codigo = "ING601",
                            Creditos = 4,
                            CuposMaximos = 30,
                            Nombre = "Ingeniería de Software",
                            Semestre = 6
                        },
                        new
                        {
                            Id = 12,
                            CarreraId = 2,
                            Codigo = "ADM101",
                            Creditos = 3,
                            CuposMaximos = 30,
                            Nombre = "Contabilidad",
                            Semestre = 1
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Prerrequisito", b =>
                {
                    b.Property<int>("MateriaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_id");

                    b.Property<int>("MateriaRequisitoId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_requisito_id");

                    b.HasKey("MateriaId", "MateriaRequisitoId")
                        .HasName("pk_prerrequisitos");

                    b.HasIndex("MateriaRequisitoId")
                        .HasDatabaseName("ix_prerrequisitos_materia_requisito_id");

                    b.ToTable("prerrequisitos", null, t =>
                        {
                            t.HasCheckConstraint("ck_prerrequisitos_no_self", "materia_id <> materia_requisito_id");
                        });

                    b.HasData(
                        new
                        {
                            MateriaId = 6,
                            MateriaRequisitoId = 1
                        },
                        new
                        {
                            MateriaId = 7,
                            MateriaRequisitoId = 3
                        },
                        new
                        {
                            MateriaId = 10,
                            MateriaRequisitoId = 7
                        });
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("MsInscripcion.Domain.Entities.Carrera", "Carrera")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estudiantes_carreras_carrera_id");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.HistorialAcademico", b =>
                {
                    b.HasOne("MsInscripcion.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Historial")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_academico_estudiantes_estudiante_id");

                    b.HasOne("MsInscripcion.Domain.Entities.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_academico_materias_materia_id");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.HorarioMateria", b =>
                {
                    b.HasOne("MsInscripcion.Domain.Entities.Materia", "Materia")
                        .WithMany("Horarios")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horario_materia_materias_materia_id");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("MsInscripcion.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_estudiantes_estudiante_id");

                    b.HasOne("MsInscripcion.Domain.Entities.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_materias_materia_id");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Materia", b =>
                {
                    b.HasOne("MsInscripcion.Domain.Entities.Carrera", "Carrera")
                        .WithMany("Materias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materias_carreras_carrera_id");

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Prerrequisito", b =>
                {
                    b.HasOne("MsInscripcion.Domain.Entities.Materia", "Materia")
                        .WithMany("Prerrequisitos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prerrequisitos_materias_materia_id");

                    b.HasOne("MsInscripcion.Domain.Entities.Materia", "MateriaRequisito")
                        .WithMany()
                        .HasForeignKey("MateriaRequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prerrequisitos_materias_materia_requisito_id");

                    b.Navigation("Materia");

                    b.Navigation("MateriaRequisito");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Carrera", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Historial");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("MsInscripcion.Domain.Entities.Materia", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Prerrequisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
