using MsInscripcion.Domain.Entities;
using MsInscripcion.Domain.Enums;

namespace MsInscripcion.Infrastructure.Persistence.Seed;

/// <summary>
/// Deterministic demo data (period 2026-2) applied through HasData. Curriculum: Unillanos Ingeniería de Sistemas
/// (src/data/mocks/malla_curricular.json) plus a minimal second carrera.
/// Ids are explicit; identity sequences start at <see cref="IdentityStart"/> so new rows never collide with the seed.
/// </summary>
public static class SeedData
{
    /// <summary>First value generated by the identity columns (above every seeded id).</summary>
    public const long IdentityStart = 1000;

    private static readonly DateTimeOffset SeedMoment = new(2026, 8, 1, 12, 0, 0, TimeSpan.Zero);

    public static readonly Carrera[] Carreras =
    [
        new() { Id = 1, Codigo = "ING-SIS", Nombre = "Ingeniería de Sistemas", DuracionSemestres = 10 },
        new() { Id = 2, Codigo = "ADM", Nombre = "Administración de Empresas", DuracionSemestres = 8 }
    ];

    public static readonly Materia[] Materias =
    [
        new() { Id = 1, Codigo = "603101", Nombre = "Algoritmia y Programación", Creditos = 4, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 2, Codigo = "603102", Nombre = "Introducción a la Ingeniería de Sistemas", Creditos = 4, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 3, Codigo = "603103", Nombre = "Cálculo Diferencial", Creditos = 4, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 4, Codigo = "603104", Nombre = "Desarrollo del Pensamiento Lógico Matemático", Creditos = 2, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 5, Codigo = "603105", Nombre = "Procesos Comunicativos", Creditos = 2, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 6, Codigo = "603201", Nombre = "Programación Orientada A Objetos", Creditos = 4, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 7, Codigo = "603202", Nombre = "Sistemas Digitales", Creditos = 3, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 8, Codigo = "603203", Nombre = "Cálculo Integral", Creditos = 4, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 9, Codigo = "603204", Nombre = "Álgebra Lineal", Creditos = 3, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 10, Codigo = "603205", Nombre = "Física Mecánica", Creditos = 4, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 11, Codigo = "603301", Nombre = "Estructuras de Datos", Creditos = 4, CarreraId = 1, Semestre = 3, CuposMaximos = 30 },
        new() { Id = 12, Codigo = "603302", Nombre = "Máquinas Digitales", Creditos = 3, CarreraId = 1, Semestre = 3, CuposMaximos = 30 },
        new() { Id = 13, Codigo = "603303", Nombre = "Cálculo Multivariado", Creditos = 4, CarreraId = 1, Semestre = 3, CuposMaximos = 30 },
        new() { Id = 14, Codigo = "603304", Nombre = "Electricidad y Magnetismo", Creditos = 4, CarreraId = 1, Semestre = 3, CuposMaximos = 30 },
        new() { Id = 15, Codigo = "603305", Nombre = "Democracias y Paz", Creditos = 2, CarreraId = 1, Semestre = 3, CuposMaximos = 30 },
        new() { Id = 16, Codigo = "603401", Nombre = "Bases de Datos", Creditos = 4, CarreraId = 1, Semestre = 4, CuposMaximos = 30 },
        new() { Id = 17, Codigo = "603402", Nombre = "Sistemas Operativos", Creditos = 4, CarreraId = 1, Semestre = 4, CuposMaximos = 30 },
        new() { Id = 18, Codigo = "603403", Nombre = "Ecuaciones Diferenciales y Modelado Matemático", Creditos = 3, CarreraId = 1, Semestre = 4, CuposMaximos = 30 },
        new() { Id = 19, Codigo = "603404", Nombre = "Estadística y Probabilidad", Creditos = 4, CarreraId = 1, Semestre = 4, CuposMaximos = 30 },
        new() { Id = 20, Codigo = "603405", Nombre = "Oscilaciones y Ondas", Creditos = 3, CarreraId = 1, Semestre = 4, CuposMaximos = 30 },
        new() { Id = 21, Codigo = "603501", Nombre = "Ingeniería de Software I", Creditos = 4, CarreraId = 1, Semestre = 5, CuposMaximos = 30 },
        new() { Id = 22, Codigo = "603502", Nombre = "Pensamiento Sistémico", Creditos = 3, CarreraId = 1, Semestre = 5, CuposMaximos = 30 },
        new() { Id = 23, Codigo = "603503", Nombre = "Matemáticas Especiales", Creditos = 3, CarreraId = 1, Semestre = 5, CuposMaximos = 30 },
        new() { Id = 24, Codigo = "603504", Nombre = "Procesos Estocásticos", Creditos = 3, CarreraId = 1, Semestre = 5, CuposMaximos = 30 },
        new() { Id = 25, Codigo = "603505", Nombre = "Sistemas de Comunicaciones", Creditos = 3, CarreraId = 1, Semestre = 5, CuposMaximos = 30 },
        new() { Id = 26, Codigo = "603506", Nombre = "Ciencias, Tecnología y Desarrollo", Creditos = 2, CarreraId = 1, Semestre = 5, CuposMaximos = 30 },
        new() { Id = 27, Codigo = "603601", Nombre = "Ingeniería de Software II", Creditos = 3, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 28, Codigo = "603602", Nombre = "Métodos Numéricos", Creditos = 3, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 29, Codigo = "603603", Nombre = "Procesamiento de Señales e Imágenes", Creditos = 3, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 30, Codigo = "603604", Nombre = "Optimización", Creditos = 3, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 31, Codigo = "603605", Nombre = "Redes de Computadores", Creditos = 4, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 32, Codigo = "603606", Nombre = "Administración Financiera para Ingeniería", Creditos = 2, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 33, Codigo = "603701", Nombre = "Metodología de Investigación", Creditos = 3, CarreraId = 1, Semestre = 7, CuposMaximos = 30 },
        new() { Id = 34, Codigo = "603702", Nombre = "Tecnologías Avanzadas", Creditos = 3, CarreraId = 1, Semestre = 7, CuposMaximos = 30 },
        new() { Id = 35, Codigo = "603703", Nombre = "Ética y Humanística", Creditos = 2, CarreraId = 1, Semestre = 7, CuposMaximos = 30 },
        new() { Id = 36, Codigo = "603704", Nombre = "Sistemas Distribuidos", Creditos = 3, CarreraId = 1, Semestre = 7, CuposMaximos = 30 },
        new() { Id = 37, Codigo = "603705", Nombre = "Seguridad de la Información", Creditos = 3, CarreraId = 1, Semestre = 7, CuposMaximos = 30 },
        new() { Id = 38, Codigo = "603706", Nombre = "Formulación y Gestión de Proyectos TI", Creditos = 3, CarreraId = 1, Semestre = 7, CuposMaximos = 30 },
        new() { Id = 39, Codigo = "603801", Nombre = "Curso I Profundización", Creditos = 3, CarreraId = 1, Semestre = 8, CuposMaximos = 30 },
        new() { Id = 40, Codigo = "603802", Nombre = "Electiva Profesional I", Creditos = 3, CarreraId = 1, Semestre = 8, CuposMaximos = 30 },
        new() { Id = 41, Codigo = "603803", Nombre = "Simulación Computacional", Creditos = 3, CarreraId = 1, Semestre = 8, CuposMaximos = 30 },
        new() { Id = 42, Codigo = "603804", Nombre = "Arquitectura Empresarial", Creditos = 3, CarreraId = 1, Semestre = 8, CuposMaximos = 30 },
        new() { Id = 43, Codigo = "603805", Nombre = "Trabajo de Grado I", Creditos = 2, CarreraId = 1, Semestre = 8, CuposMaximos = 30 },
        new() { Id = 44, Codigo = "603806", Nombre = "Cátedra Orinoquia", Creditos = 2, CarreraId = 1, Semestre = 8, CuposMaximos = 30 },
        new() { Id = 45, Codigo = "603901", Nombre = "Curso Ii Profundización", Creditos = 3, CarreraId = 1, Semestre = 9, CuposMaximos = 30 },
        new() { Id = 46, Codigo = "603902", Nombre = "Electiva Profesional Ii", Creditos = 3, CarreraId = 1, Semestre = 9, CuposMaximos = 30 },
        new() { Id = 47, Codigo = "603903", Nombre = "Electiva Profesional Iii", Creditos = 3, CarreraId = 1, Semestre = 9, CuposMaximos = 1 },
        new() { Id = 48, Codigo = "603904", Nombre = "Lenguajes de Programación", Creditos = 3, CarreraId = 1, Semestre = 9, CuposMaximos = 30 },
        new() { Id = 49, Codigo = "603905", Nombre = "Electiva Profesional Iv", Creditos = 3, CarreraId = 1, Semestre = 9, CuposMaximos = 30 },
        new() { Id = 50, Codigo = "603001", Nombre = "Curso Iii Profundización", Creditos = 3, CarreraId = 1, Semestre = 10, CuposMaximos = 30 },
        new() { Id = 51, Codigo = "603002", Nombre = "Electiva Profesional V", Creditos = 3, CarreraId = 1, Semestre = 10, CuposMaximos = 30 },
        new() { Id = 52, Codigo = "603003", Nombre = "Trabajo de Grado Ii", Creditos = 4, CarreraId = 1, Semestre = 10, CuposMaximos = 30 },
        new() { Id = 53, Codigo = "603004", Nombre = "Electiva Complementaria", Creditos = 2, CarreraId = 1, Semestre = 10, CuposMaximos = 30 },
        new() { Id = 54, Codigo = "ADM101", Nombre = "Contabilidad", Creditos = 3, CarreraId = 2, Semestre = 1, CuposMaximos = 30 }
    ];

    public static readonly HorarioMateria[] Horarios =
    [
        Block(1, 1, DiaSemana.Lunes, 7, 9),
        Block(2, 1, DiaSemana.Miercoles, 7, 9),
        Block(3, 2, DiaSemana.Lunes, 9, 11),
        Block(4, 2, DiaSemana.Miercoles, 9, 11),
        Block(5, 3, DiaSemana.Martes, 7, 9),
        Block(6, 3, DiaSemana.Jueves, 7, 9),
        Block(7, 4, DiaSemana.Martes, 9, 11),
        Block(8, 4, DiaSemana.Jueves, 9, 11),
        Block(9, 5, DiaSemana.Viernes, 7, 11),
        Block(10, 6, DiaSemana.Lunes, 14, 16),
        Block(11, 6, DiaSemana.Miercoles, 14, 16),
        Block(12, 7, DiaSemana.Lunes, 16, 18),
        Block(13, 7, DiaSemana.Miercoles, 16, 18),
        Block(14, 8, DiaSemana.Martes, 14, 16),
        Block(15, 8, DiaSemana.Jueves, 14, 16),
        Block(16, 9, DiaSemana.Martes, 16, 18),
        Block(17, 9, DiaSemana.Jueves, 16, 18),
        Block(18, 10, DiaSemana.Viernes, 14, 18),
        Block(19, 11, DiaSemana.Lunes, 7, 9),
        Block(20, 11, DiaSemana.Miercoles, 7, 9),
        Block(21, 12, DiaSemana.Lunes, 9, 11),
        Block(22, 12, DiaSemana.Miercoles, 9, 11),
        Block(23, 13, DiaSemana.Martes, 7, 9),
        Block(24, 13, DiaSemana.Jueves, 7, 9),
        Block(25, 14, DiaSemana.Martes, 9, 11),
        Block(26, 14, DiaSemana.Jueves, 9, 11),
        Block(27, 15, DiaSemana.Sabado, 11, 13),
        Block(28, 16, DiaSemana.Lunes, 14, 16),
        Block(29, 16, DiaSemana.Miercoles, 14, 16),
        Block(30, 17, DiaSemana.Lunes, 16, 18),
        Block(31, 17, DiaSemana.Miercoles, 16, 18),
        Block(32, 18, DiaSemana.Martes, 14, 16),
        Block(33, 18, DiaSemana.Jueves, 14, 16),
        Block(34, 19, DiaSemana.Martes, 16, 18),
        Block(35, 19, DiaSemana.Jueves, 16, 18),
        Block(36, 20, DiaSemana.Viernes, 14, 18),
        Block(37, 21, DiaSemana.Lunes, 7, 9),
        Block(38, 21, DiaSemana.Miercoles, 7, 9),
        Block(39, 22, DiaSemana.Lunes, 9, 11),
        Block(40, 22, DiaSemana.Miercoles, 9, 11),
        Block(41, 23, DiaSemana.Martes, 7, 9),
        Block(42, 23, DiaSemana.Jueves, 7, 9),
        Block(43, 24, DiaSemana.Martes, 9, 11),
        Block(44, 24, DiaSemana.Jueves, 9, 11),
        Block(45, 25, DiaSemana.Viernes, 7, 11),
        Block(46, 26, DiaSemana.Sabado, 7, 11),
        Block(47, 27, DiaSemana.Lunes, 14, 16),
        Block(48, 27, DiaSemana.Miercoles, 14, 16),
        Block(49, 28, DiaSemana.Lunes, 16, 18),
        Block(50, 28, DiaSemana.Miercoles, 16, 18),
        Block(51, 29, DiaSemana.Martes, 14, 16),
        Block(52, 29, DiaSemana.Jueves, 14, 16),
        Block(53, 30, DiaSemana.Martes, 16, 18),
        Block(54, 30, DiaSemana.Jueves, 16, 18),
        Block(55, 31, DiaSemana.Viernes, 14, 18),
        Block(56, 32, DiaSemana.Sabado, 14, 18),
        Block(57, 33, DiaSemana.Lunes, 7, 9),
        Block(58, 33, DiaSemana.Miercoles, 7, 9),
        Block(59, 34, DiaSemana.Lunes, 9, 11),
        Block(60, 34, DiaSemana.Miercoles, 9, 11),
        Block(61, 35, DiaSemana.Martes, 7, 9),
        Block(62, 35, DiaSemana.Jueves, 7, 9),
        Block(63, 36, DiaSemana.Martes, 9, 11),
        Block(64, 36, DiaSemana.Jueves, 9, 11),
        Block(65, 37, DiaSemana.Viernes, 7, 11),
        Block(66, 38, DiaSemana.Sabado, 7, 11),
        Block(67, 39, DiaSemana.Lunes, 14, 16),
        Block(68, 39, DiaSemana.Miercoles, 14, 16),
        Block(69, 40, DiaSemana.Lunes, 16, 18),
        Block(70, 40, DiaSemana.Miercoles, 16, 18),
        Block(71, 41, DiaSemana.Martes, 14, 16),
        Block(72, 41, DiaSemana.Jueves, 14, 16),
        Block(73, 42, DiaSemana.Martes, 16, 18),
        Block(74, 42, DiaSemana.Jueves, 16, 18),
        Block(75, 43, DiaSemana.Viernes, 14, 18),
        Block(76, 44, DiaSemana.Sabado, 14, 18),
        Block(77, 45, DiaSemana.Lunes, 7, 9),
        Block(78, 45, DiaSemana.Miercoles, 7, 9),
        Block(79, 46, DiaSemana.Lunes, 14, 16),
        Block(80, 46, DiaSemana.Miercoles, 14, 16),
        Block(81, 47, DiaSemana.Martes, 7, 9),
        Block(82, 47, DiaSemana.Jueves, 7, 9),
        Block(83, 48, DiaSemana.Martes, 9, 11),
        Block(84, 48, DiaSemana.Jueves, 9, 11),
        Block(85, 49, DiaSemana.Viernes, 7, 11),
        Block(86, 50, DiaSemana.Viernes, 14, 18),
        Block(87, 51, DiaSemana.Lunes, 16, 18),
        Block(88, 51, DiaSemana.Miercoles, 16, 18),
        Block(89, 52, DiaSemana.Martes, 14, 16),
        Block(90, 52, DiaSemana.Jueves, 14, 16),
        Block(91, 53, DiaSemana.Martes, 16, 18),
        Block(92, 53, DiaSemana.Jueves, 16, 18),
        Block(93, 54, DiaSemana.Sabado, 18, 20)
    ];

    /// <summary>MateriaId requires MateriaRequisitoId.</summary>
    public static readonly Prerrequisito[] Prerrequisitos =
    [
        new() { MateriaId = 6, MateriaRequisitoId = 1 },   // 603201 <- 603101
        new() { MateriaId = 8, MateriaRequisitoId = 3 },   // 603203 <- 603103
        new() { MateriaId = 10, MateriaRequisitoId = 3 },   // 603205 <- 603103
        new() { MateriaId = 11, MateriaRequisitoId = 6 },   // 603301 <- 603201
        new() { MateriaId = 12, MateriaRequisitoId = 7 },   // 603302 <- 603202
        new() { MateriaId = 13, MateriaRequisitoId = 8 },   // 603303 <- 603203
        new() { MateriaId = 13, MateriaRequisitoId = 9 },   // 603303 <- 603204
        new() { MateriaId = 14, MateriaRequisitoId = 10 },   // 603304 <- 603205
        new() { MateriaId = 16, MateriaRequisitoId = 11 },   // 603401 <- 603301
        new() { MateriaId = 17, MateriaRequisitoId = 11 },   // 603402 <- 603301
        new() { MateriaId = 17, MateriaRequisitoId = 12 },   // 603402 <- 603302
        new() { MateriaId = 18, MateriaRequisitoId = 13 },   // 603403 <- 603303
        new() { MateriaId = 19, MateriaRequisitoId = 13 },   // 603404 <- 603303
        new() { MateriaId = 20, MateriaRequisitoId = 14 },   // 603405 <- 603304
        new() { MateriaId = 21, MateriaRequisitoId = 16 },   // 603501 <- 603401
        new() { MateriaId = 23, MateriaRequisitoId = 18 },   // 603503 <- 603403
        new() { MateriaId = 24, MateriaRequisitoId = 19 },   // 603504 <- 603404
        new() { MateriaId = 25, MateriaRequisitoId = 20 },   // 603505 <- 603405
        new() { MateriaId = 27, MateriaRequisitoId = 21 },   // 603601 <- 603501
        new() { MateriaId = 28, MateriaRequisitoId = 23 },   // 603602 <- 603503
        new() { MateriaId = 29, MateriaRequisitoId = 23 },   // 603603 <- 603503
        new() { MateriaId = 30, MateriaRequisitoId = 24 },   // 603604 <- 603504
        new() { MateriaId = 31, MateriaRequisitoId = 25 },   // 603605 <- 603505
        new() { MateriaId = 33, MateriaRequisitoId = 22 },   // 603701 <- 603502
        new() { MateriaId = 34, MateriaRequisitoId = 27 },   // 603702 <- 603601
        new() { MateriaId = 36, MateriaRequisitoId = 31 },   // 603704 <- 603605
        new() { MateriaId = 37, MateriaRequisitoId = 31 },   // 603705 <- 603605
        new() { MateriaId = 38, MateriaRequisitoId = 32 },   // 603706 <- 603606
        new() { MateriaId = 41, MateriaRequisitoId = 22 },   // 603803 <- 603502
        new() { MateriaId = 43, MateriaRequisitoId = 33 },   // 603805 <- 603701
        new() { MateriaId = 45, MateriaRequisitoId = 39 },   // 603901 <- 603801
        new() { MateriaId = 50, MateriaRequisitoId = 45 },   // 603001 <- 603901
        new() { MateriaId = 52, MateriaRequisitoId = 43 }    // 603003 <- 603805
    ];

    public static readonly Estudiante[] Estudiantes =
    [
        new() { Id = 1, Nombre = "Laura Gómez Ríos", CarreraId = 1, SemestreActual = 6 },
        new() { Id = 2, Nombre = "Mateo Rojas Herrera", CarreraId = 1, SemestreActual = 7 },
        new() { Id = 3, Nombre = "Camila Torres Vargas", CarreraId = 1, SemestreActual = 7 },
        new() { Id = 4, Nombre = "Sofía Martínez Ruiz", CarreraId = 1, SemestreActual = 8 },
        new() { Id = 5, Nombre = "Andrés Pérez Molina", CarreraId = 1, SemestreActual = 9 }
    ];

    public static readonly HistorialAcademico[] Historial =
    [
        new() { Id = 1, EstudianteId = 1, MateriaId = 1, Estado = EstadoHistorial.Aprobada, Nota = 4.5m, Periodo = "2024-1" },
        new() { Id = 2, EstudianteId = 1, MateriaId = 2, Estado = EstadoHistorial.Aprobada, Nota = 4.2m, Periodo = "2024-1" },
        new() { Id = 3, EstudianteId = 1, MateriaId = 3, Estado = EstadoHistorial.Aprobada, Nota = 4.2m, Periodo = "2024-1" },
        new() { Id = 4, EstudianteId = 1, MateriaId = 4, Estado = EstadoHistorial.Aprobada, Nota = 3.8m, Periodo = "2024-1" },
        new() { Id = 5, EstudianteId = 1, MateriaId = 5, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 6, EstudianteId = 1, MateriaId = 6, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 7, EstudianteId = 1, MateriaId = 7, Estado = EstadoHistorial.Aprobada, Nota = 3.9m, Periodo = "2024-2" },
        new() { Id = 8, EstudianteId = 1, MateriaId = 8, Estado = EstadoHistorial.Aprobada, Nota = 3.8m, Periodo = "2024-2" },
        new() { Id = 9, EstudianteId = 1, MateriaId = 9, Estado = EstadoHistorial.Aprobada, Nota = 3.6m, Periodo = "2024-2" },
        new() { Id = 10, EstudianteId = 1, MateriaId = 10, Estado = EstadoHistorial.Aprobada, Nota = 3.4m, Periodo = "2024-2" },
        new() { Id = 11, EstudianteId = 1, MateriaId = 11, Estado = EstadoHistorial.Aprobada, Nota = 4.1m, Periodo = "2025-1" },
        new() { Id = 12, EstudianteId = 1, MateriaId = 12, Estado = EstadoHistorial.Aprobada, Nota = 3.7m, Periodo = "2025-1" },
        new() { Id = 13, EstudianteId = 1, MateriaId = 13, Estado = EstadoHistorial.Aprobada, Nota = 3.9m, Periodo = "2025-1" },
        new() { Id = 14, EstudianteId = 1, MateriaId = 14, Estado = EstadoHistorial.Aprobada, Nota = 3.5m, Periodo = "2025-1" },
        new() { Id = 15, EstudianteId = 1, MateriaId = 15, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 16, EstudianteId = 1, MateriaId = 16, Estado = EstadoHistorial.Aprobada, Nota = 3.7m, Periodo = "2025-2" },
        new() { Id = 17, EstudianteId = 1, MateriaId = 17, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 18, EstudianteId = 1, MateriaId = 18, Estado = EstadoHistorial.Aprobada, Nota = 3.3m, Periodo = "2025-2" },
        new() { Id = 19, EstudianteId = 1, MateriaId = 19, Estado = EstadoHistorial.Aprobada, Nota = 3.8m, Periodo = "2025-2" },
        new() { Id = 20, EstudianteId = 1, MateriaId = 20, Estado = EstadoHistorial.Aprobada, Nota = 3.6m, Periodo = "2025-2" },
        new() { Id = 21, EstudianteId = 1, MateriaId = 21, Estado = EstadoHistorial.Aprobada, Nota = 3.9m, Periodo = "2026-1" },
        new() { Id = 22, EstudianteId = 1, MateriaId = 22, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 23, EstudianteId = 1, MateriaId = 23, Estado = EstadoHistorial.Aprobada, Nota = 3.4m, Periodo = "2026-1" },
        new() { Id = 24, EstudianteId = 1, MateriaId = 24, Estado = EstadoHistorial.Aprobada, Nota = 3.7m, Periodo = "2026-1" },
        new() { Id = 25, EstudianteId = 1, MateriaId = 25, Estado = EstadoHistorial.Aprobada, Nota = 3.5m, Periodo = "2026-1" },
        new() { Id = 26, EstudianteId = 1, MateriaId = 26, Estado = EstadoHistorial.Aprobada, Nota = 3.8m, Periodo = "2026-1" },
        new() { Id = 27, EstudianteId = 2, MateriaId = 1, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 28, EstudianteId = 2, MateriaId = 2, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 29, EstudianteId = 2, MateriaId = 3, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 30, EstudianteId = 2, MateriaId = 4, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 31, EstudianteId = 2, MateriaId = 5, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 32, EstudianteId = 2, MateriaId = 6, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 33, EstudianteId = 2, MateriaId = 7, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 34, EstudianteId = 2, MateriaId = 8, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 35, EstudianteId = 2, MateriaId = 9, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 36, EstudianteId = 2, MateriaId = 10, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 37, EstudianteId = 2, MateriaId = 11, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 38, EstudianteId = 2, MateriaId = 12, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 39, EstudianteId = 2, MateriaId = 13, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 40, EstudianteId = 2, MateriaId = 14, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 41, EstudianteId = 2, MateriaId = 15, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 42, EstudianteId = 2, MateriaId = 16, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 43, EstudianteId = 2, MateriaId = 17, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 44, EstudianteId = 2, MateriaId = 18, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 45, EstudianteId = 2, MateriaId = 19, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 46, EstudianteId = 2, MateriaId = 20, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 47, EstudianteId = 2, MateriaId = 21, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 48, EstudianteId = 2, MateriaId = 22, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 49, EstudianteId = 2, MateriaId = 23, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 50, EstudianteId = 2, MateriaId = 24, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 51, EstudianteId = 2, MateriaId = 25, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 52, EstudianteId = 2, MateriaId = 26, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 53, EstudianteId = 2, MateriaId = 27, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 54, EstudianteId = 2, MateriaId = 28, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 55, EstudianteId = 2, MateriaId = 29, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 56, EstudianteId = 2, MateriaId = 30, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 57, EstudianteId = 2, MateriaId = 31, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 58, EstudianteId = 2, MateriaId = 32, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 59, EstudianteId = 3, MateriaId = 1, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 60, EstudianteId = 3, MateriaId = 2, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 61, EstudianteId = 3, MateriaId = 3, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 62, EstudianteId = 3, MateriaId = 4, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 63, EstudianteId = 3, MateriaId = 5, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 64, EstudianteId = 3, MateriaId = 6, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 65, EstudianteId = 3, MateriaId = 7, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 66, EstudianteId = 3, MateriaId = 8, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 67, EstudianteId = 3, MateriaId = 9, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 68, EstudianteId = 3, MateriaId = 10, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 69, EstudianteId = 3, MateriaId = 11, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 70, EstudianteId = 3, MateriaId = 12, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 71, EstudianteId = 3, MateriaId = 13, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 72, EstudianteId = 3, MateriaId = 14, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 73, EstudianteId = 3, MateriaId = 15, Estado = EstadoHistorial.Reprobada, Nota = 2.5m, Periodo = "2024-2" },
        new() { Id = 74, EstudianteId = 3, MateriaId = 16, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 75, EstudianteId = 3, MateriaId = 17, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 76, EstudianteId = 3, MateriaId = 18, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 77, EstudianteId = 3, MateriaId = 19, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 78, EstudianteId = 3, MateriaId = 20, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 79, EstudianteId = 3, MateriaId = 21, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 80, EstudianteId = 3, MateriaId = 22, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 81, EstudianteId = 3, MateriaId = 23, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 82, EstudianteId = 3, MateriaId = 24, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 83, EstudianteId = 3, MateriaId = 25, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 84, EstudianteId = 3, MateriaId = 26, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 85, EstudianteId = 3, MateriaId = 27, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 86, EstudianteId = 3, MateriaId = 28, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 87, EstudianteId = 3, MateriaId = 29, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 88, EstudianteId = 3, MateriaId = 30, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 89, EstudianteId = 3, MateriaId = 31, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 90, EstudianteId = 3, MateriaId = 32, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 91, EstudianteId = 4, MateriaId = 1, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 92, EstudianteId = 4, MateriaId = 2, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 93, EstudianteId = 4, MateriaId = 3, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 94, EstudianteId = 4, MateriaId = 4, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 95, EstudianteId = 4, MateriaId = 5, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 96, EstudianteId = 4, MateriaId = 6, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 97, EstudianteId = 4, MateriaId = 7, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 98, EstudianteId = 4, MateriaId = 8, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 99, EstudianteId = 4, MateriaId = 9, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 100, EstudianteId = 4, MateriaId = 10, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 101, EstudianteId = 4, MateriaId = 11, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 102, EstudianteId = 4, MateriaId = 12, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 103, EstudianteId = 4, MateriaId = 13, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 104, EstudianteId = 4, MateriaId = 14, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 105, EstudianteId = 4, MateriaId = 15, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 106, EstudianteId = 4, MateriaId = 16, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 107, EstudianteId = 4, MateriaId = 17, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 108, EstudianteId = 4, MateriaId = 18, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 109, EstudianteId = 4, MateriaId = 19, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 110, EstudianteId = 4, MateriaId = 20, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 111, EstudianteId = 4, MateriaId = 21, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 112, EstudianteId = 4, MateriaId = 22, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 113, EstudianteId = 4, MateriaId = 23, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 114, EstudianteId = 4, MateriaId = 24, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 115, EstudianteId = 4, MateriaId = 25, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 116, EstudianteId = 4, MateriaId = 26, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 117, EstudianteId = 4, MateriaId = 27, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 118, EstudianteId = 4, MateriaId = 28, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 119, EstudianteId = 4, MateriaId = 29, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 120, EstudianteId = 4, MateriaId = 30, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 121, EstudianteId = 4, MateriaId = 31, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 122, EstudianteId = 4, MateriaId = 32, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 123, EstudianteId = 4, MateriaId = 33, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 124, EstudianteId = 4, MateriaId = 34, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 125, EstudianteId = 4, MateriaId = 35, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 126, EstudianteId = 4, MateriaId = 36, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 127, EstudianteId = 4, MateriaId = 37, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 128, EstudianteId = 4, MateriaId = 38, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 129, EstudianteId = 5, MateriaId = 1, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2022-2" },
        new() { Id = 130, EstudianteId = 5, MateriaId = 2, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2022-2" },
        new() { Id = 131, EstudianteId = 5, MateriaId = 3, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2022-2" },
        new() { Id = 132, EstudianteId = 5, MateriaId = 4, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2022-2" },
        new() { Id = 133, EstudianteId = 5, MateriaId = 5, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2022-2" },
        new() { Id = 134, EstudianteId = 5, MateriaId = 6, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 135, EstudianteId = 5, MateriaId = 7, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 136, EstudianteId = 5, MateriaId = 8, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 137, EstudianteId = 5, MateriaId = 9, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 138, EstudianteId = 5, MateriaId = 10, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-1" },
        new() { Id = 139, EstudianteId = 5, MateriaId = 11, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 140, EstudianteId = 5, MateriaId = 12, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 141, EstudianteId = 5, MateriaId = 13, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 142, EstudianteId = 5, MateriaId = 14, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 143, EstudianteId = 5, MateriaId = 15, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2023-2" },
        new() { Id = 144, EstudianteId = 5, MateriaId = 16, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 145, EstudianteId = 5, MateriaId = 17, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 146, EstudianteId = 5, MateriaId = 18, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 147, EstudianteId = 5, MateriaId = 19, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 148, EstudianteId = 5, MateriaId = 20, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-1" },
        new() { Id = 149, EstudianteId = 5, MateriaId = 21, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 150, EstudianteId = 5, MateriaId = 22, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 151, EstudianteId = 5, MateriaId = 23, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 152, EstudianteId = 5, MateriaId = 24, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 153, EstudianteId = 5, MateriaId = 25, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 154, EstudianteId = 5, MateriaId = 26, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2024-2" },
        new() { Id = 155, EstudianteId = 5, MateriaId = 27, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 156, EstudianteId = 5, MateriaId = 28, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 157, EstudianteId = 5, MateriaId = 29, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 158, EstudianteId = 5, MateriaId = 30, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 159, EstudianteId = 5, MateriaId = 31, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 160, EstudianteId = 5, MateriaId = 32, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-1" },
        new() { Id = 161, EstudianteId = 5, MateriaId = 33, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 162, EstudianteId = 5, MateriaId = 34, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 163, EstudianteId = 5, MateriaId = 35, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 164, EstudianteId = 5, MateriaId = 36, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 165, EstudianteId = 5, MateriaId = 37, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 166, EstudianteId = 5, MateriaId = 38, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2025-2" },
        new() { Id = 167, EstudianteId = 5, MateriaId = 39, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 168, EstudianteId = 5, MateriaId = 40, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 169, EstudianteId = 5, MateriaId = 41, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 170, EstudianteId = 5, MateriaId = 42, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 171, EstudianteId = 5, MateriaId = 43, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 172, EstudianteId = 5, MateriaId = 44, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" }
    ];

    public static readonly Inscripcion[] Inscripciones =
    [
        new()
        {
            Id = 1, EstudianteId = 5, MateriaId = 47, PeriodoAcademico = "2026-2",
            Estado = EstadoInscripcion.Activa, FechaInscripcion = SeedMoment
        }
    ];

    private static HorarioMateria Block(int id, int materiaId, DiaSemana dia, int startHour, int endHour) => new()
    {
        Id = id,
        MateriaId = materiaId,
        DiaSemana = dia,
        HoraInicio = new TimeOnly(startHour, 0),
        HoraFin = new TimeOnly(endHour, 0)
    };
}
