using MsInscripcion.Domain.Entities;
using MsInscripcion.Domain.Enums;

namespace MsInscripcion.Infrastructure.Persistence.Seed;

/// <summary>
/// Deterministic demo data (period 2026-2) applied through HasData in the InitialCreate migration.
/// Ids are explicit; identity sequences start at <see cref="IdentityStart"/> so new rows never collide with the seed.
/// </summary>
public static class SeedData
{
    /// <summary>First value generated by the identity columns (above every seeded id).</summary>
    public const long IdentityStart = 1000;

    private static readonly DateTimeOffset SeedMoment = new(2026, 8, 1, 12, 0, 0, TimeSpan.Zero);

    public static readonly Carrera[] Carreras =
    [
        new() { Id = 1, Codigo = "ING-SIS", Nombre = "Ingeniería de Sistemas", DuracionSemestres = 10 },
        new() { Id = 2, Codigo = "ADM", Nombre = "Administración de Empresas", DuracionSemestres = 8 }
    ];

    public static readonly Materia[] Materias =
    [
        new() { Id = 1, Codigo = "MAT101", Nombre = "Cálculo I", Creditos = 4, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 2, Codigo = "FIS101", Nombre = "Física I", Creditos = 4, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 3, Codigo = "PRG101", Nombre = "Programación I", Creditos = 4, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 4, Codigo = "ETI101", Nombre = "Ética", Creditos = 2, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 5, Codigo = "HUM101", Nombre = "Humanidades", Creditos = 2, CarreraId = 1, Semestre = 1, CuposMaximos = 30 },
        new() { Id = 6, Codigo = "MAT201", Nombre = "Cálculo II", Creditos = 4, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 7, Codigo = "PRG201", Nombre = "Programación II", Creditos = 4, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 8, Codigo = "EST201", Nombre = "Estadística", Creditos = 3, CarreraId = 1, Semestre = 2, CuposMaximos = 30 },
        new() { Id = 9, Codigo = "ALG201", Nombre = "Álgebra Lineal", Creditos = 3, CarreraId = 1, Semestre = 2, CuposMaximos = 1 },
        new() { Id = 10, Codigo = "EDD301", Nombre = "Estructuras de Datos", Creditos = 4, CarreraId = 1, Semestre = 3, CuposMaximos = 30 },
        new() { Id = 11, Codigo = "ING601", Nombre = "Ingeniería de Software", Creditos = 4, CarreraId = 1, Semestre = 6, CuposMaximos = 30 },
        new() { Id = 12, Codigo = "ADM101", Nombre = "Contabilidad", Creditos = 3, CarreraId = 2, Semestre = 1, CuposMaximos = 30 }
    ];

    public static readonly HorarioMateria[] Horarios =
    [
        Block(1, 1, DiaSemana.Lunes, 6, 8),
        Block(2, 1, DiaSemana.Miercoles, 6, 8),
        Block(3, 2, DiaSemana.Lunes, 9, 11),
        Block(4, 3, DiaSemana.Martes, 8, 10),
        Block(5, 4, DiaSemana.Viernes, 8, 10),
        Block(6, 5, DiaSemana.Viernes, 9, 11),
        Block(7, 6, DiaSemana.Lunes, 8, 10),
        Block(8, 6, DiaSemana.Miercoles, 10, 12),
        Block(9, 7, DiaSemana.Martes, 10, 12),
        Block(10, 7, DiaSemana.Jueves, 10, 12),
        Block(11, 8, DiaSemana.Martes, 12, 14),
        Block(12, 9, DiaSemana.Jueves, 14, 16),
        Block(13, 10, DiaSemana.Miercoles, 14, 16),
        Block(14, 11, DiaSemana.Jueves, 16, 18),
        Block(15, 12, DiaSemana.Sabado, 8, 10)
    ];

    /// <summary>MateriaId requires MateriaRequisitoId.</summary>
    public static readonly Prerrequisito[] Prerrequisitos =
    [
        new() { MateriaId = 6, MateriaRequisitoId = 1 },   // MAT201 <- MAT101
        new() { MateriaId = 7, MateriaRequisitoId = 3 },   // PRG201 <- PRG101
        new() { MateriaId = 10, MateriaRequisitoId = 7 }   // EDD301 <- PRG201
    ];

    public static readonly Estudiante[] Estudiantes =
    [
        new() { Id = 1, Nombre = "Ana", CarreraId = 1, SemestreActual = 2 },
        new() { Id = 2, Nombre = "Carlos", CarreraId = 1, SemestreActual = 1 }
    ];

    public static readonly HistorialAcademico[] Historial =
    [
        new() { Id = 1, EstudianteId = 1, MateriaId = 1, Estado = EstadoHistorial.Aprobada, Nota = 4.5m, Periodo = "2026-1" },
        new() { Id = 2, EstudianteId = 1, MateriaId = 3, Estado = EstadoHistorial.Aprobada, Nota = 4.0m, Periodo = "2026-1" },
        new() { Id = 3, EstudianteId = 1, MateriaId = 2, Estado = EstadoHistorial.Reprobada, Nota = 2.0m, Periodo = "2026-1" }
    ];

    public static readonly Inscripcion[] Inscripciones =
    [
        new()
        {
            Id = 1, EstudianteId = 1, MateriaId = 4, PeriodoAcademico = "2026-2",
            Estado = EstadoInscripcion.Activa, FechaInscripcion = SeedMoment
        },
        new()
        {
            Id = 2, EstudianteId = 2, MateriaId = 9, PeriodoAcademico = "2026-2",
            Estado = EstadoInscripcion.Activa, FechaInscripcion = SeedMoment
        }
    ];

    private static HorarioMateria Block(int id, int materiaId, DiaSemana dia, int startHour, int endHour) => new()
    {
        Id = id,
        MateriaId = materiaId,
        DiaSemana = dia,
        HoraInicio = new TimeOnly(startHour, 0),
        HoraFin = new TimeOnly(endHour, 0)
    };
}
